name: reemp_user_app
description: Reemp User application

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.4.6
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.18.0


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/